# Use the Trusty distro.
sudo: required
dist: precise

# Configure for Android.
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services
  - build-tools-19.1.0
  - android-23
  - build-tools-24.0.2
  - android-24
  licenses:
  - android-sdk-license-.+

# Setup dependencies.
before_install:
  - cd 2_ionic_app
  - nvm install 6
  - npm install -g npm cordova ionic
  - sudo apt-get install jq
install:
  - npm install

# Run the Android build.
script:
  - make test
  - make build-android
