# Use the Trusty distro.
sudo: required
dist: precise

# Configure for Android.
language: android
jdk: oraclejdk8
env:
  - BUILD_NUM=$TRAVIS_BUILD_NUMBER
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

# Setup dependencies.
before_install:
  - cd 2_ionic_app
  - nvm install 6
  - npm install -g npm cordova ionic
  - sudo apt-get install jq
install:
  - npm install

# Run the Android build.
script:
  - make touch
  - make test
  - make label
  - make build-android

# Deploy master.
deploy:
  skip_cleanup: true # Don't reset the working directory!
  provider: script
  script: make deploy-android
  on:
    branch: master
