language: objective-c
os: osx  
osx_image: xcode8
before_install:
  - brew update
  - brew install jq
  - npm install -g npm cordova ionic
script:
  - cd 2_ionic_app
  - make test
  - make build-android
