# Use the Trusty distro.
sudo: required
dist: trusty

# Configure for Android.
language: android
android:
  components:
    - build-tools-19.1.0
    - android-23

# Setup dependencies.
before_install:
  - cd 2_ionic_app
  - nvm install 6
  - npm install -g npm cordova ionic
  - sudo apt-get install jq
install:
  - npm install

# Run the Android build.
script:
  - make test
  - make build-android
