language: android
android:
  components:
    - build-tools-19.1.0
    - android-23
before_install:
  - cd 2_ionic_app
  - nvm install 6
  - sudo apt-get install jq
  - npm install -g npm cordova ionic
install:
  - npm install
script:
  - make test
  - make build-android
