# Support container based architecture.
sudo: false

# Ensure we have JDK 1.8.
addons:
  apt:
    packages:
      - oracle-java8-installer    # JDK 1.8
      - jq                        # JSON Query

# Configure for Android.
language: android
android:
  components:
    - build-tools-19.1.0
    - android-23

# Setup dependencies.
before_install:
  - cd 2_ionic_app
  - nvm install 6
  - npm install -g npm cordova ionic
install:
  - npm install

# Run the Android build.
script:
  - make test
  - make build-android
